using cleansing;

$persons_duplicate_pairs = read from 'src/test/resources/FusionITTestData.json';

$persons_fused = fuse $p in $persons_duplicate_pairs
	with weights {
		nsa: 0.61,
		bnd: 0.9,
		mossad: 0.3,
		cia : 0.7*{addresses: 0.8*{street:0.7, zipcode: 0.9}, name: 0.3}
	}
	with resolutions {
		name: [mostFrequent, defaultResolution("default")],
		//name: mostFrequent,
		//name: [defaultResolution("default")],
		
		age: mergeDistinct
};

write $persons_fused to 'file:///tmp/FusionITTestOutput.json';

