using cleansing;

$originalPersons = read from 'src/test/resources/MappingIT5TestOriginalPersons.json';

$persons, $companies  = map entities of $originalPersons
	into [
	    entity $persons identified by $originalPersons.id with {
	    	name: $originalPersons.name,
	    	worksFor: $companies.id
	    }, 
	    entity $companies identified by $originalPersons.worksFor with {
		}
	];

write $persons to 'file:///tmp/MappingIT5TestOutputPersons.json';
write $companies to 'file:///tmp/MappingIT5aTestOutputCompanies.json';