using cleansing;

$originalPersons = read from 'src/test/resources/MappingIT4TestOriginalPersons.json';

$persons, $companies  = map entities of $originalPersons
	into [
	    entity $companies identified by $originalPersons.worksFor with {
	       name: $originalPersons.worksFor
	    },
	    entity $persons identified by $originalPersons.id with {
	    	name: $originalPersons.name,
	    	worksFor: $companies.id
	    }
	];

write $persons to 'file:///tmp/MappingIT4TestOutputPersons.json';
write $companies to 'file:///tmp/MappingIT4TestOutputCompanies.json';