using cleansing;

$usCongressMembers = read from 'MappingITTestUsCongressMembers2.json';
$usCongressBiographies = read from 'MappingITTestUsCongressBiography2.json';

$person, $legalEntity  = map entities from $usCongressMembers, $usCongressBiographies where ($usCongressMembers.biography[1:1] == $usCongressBiographies.biographyId[1:1])
	as [
	    group $usCongressMembers by $usCongressMembers.id into {
	    	name: $usCongressMembers.name,
	    	worksFor: $legalEntity.id
	    },
	    group $usCongressBiographies by $usCongressBiographies.worksFor into {
	       name: $usCongressBiographies.worksFor
	    }
	];

write $person to 'file:///tmp/MappingITTestOutputPersons2.json';
write $legalEntity to 'file:///tmp/MappingITTestOutputLegalEntities2.json';