using cleansing;

$originalPersons = read from 'MappingIT3TestOriginalPersons.json';
$originalJobs = read from 'MappingIT3TestOriginalJobs.json';

$persons  = map entities of $originalPersons, $originalJobs where ($originalPersons.job == $originalJobs.id)
	into [
	    entity $originalPersons identified by $originalPersons.id with {
	    	name: concat_strings($originalPersons.name, '-', $originalJobs.title)
	    }
	];

write $persons to 'file:///tmp/MappingIT3aTestOutputPersons.json';
