using cleansing;

$originalPersons = read from 'MappingIT3TestOriginalPersons.json';

$persons  = map entities from $originalPersons
	as [
	    group $originalPersons by $originalPersons.id into {
	    	name: $originalPersons.name,
	    	address: {
	    		street: $originalPersons.street,
	    		zip: $originalPersons.zip
	    	}
	    }
	];

write $persons to 'file:///tmp/MappingIT3TestOutputPersons.json';
