using cleansing;

$originalPersons = read from 'src/test/resources/MappingIT2TestOriginalPersons.json';

$persons, $companies  = map entities of $originalPersons
	into [
	    entity $originalPersons identified by $originalPersons.id with {
	    	name: $originalPersons.name,
	    	worksFor: $companies.id
	    },
	    entity $originalPersons identified by $originalPersons.worksFor with {
	       name: $originalPersons.worksFor
	    }
	];

write $persons to 'file:///tmp/MappingIT2TestOutputPersons.json';
write $companies to 'file:///tmp/MappingIT2TestOutputCompanies.json';