using cleansing;

$usCongressMembers = read from 'MappingITTestUsCongressMembers.json';
$usCongressBiographies = read from 'MappingITTestUsCongressBiography.json';

$person, $legalEntity  = map entities of $usCongressMembers, $usCongressBiographies where ($usCongressMembers.biography[1:1] == $usCongressBiographies.biographyId[1:1])
	into [
	    entity $person identified by $usCongressMembers.id with {
	    	name: $usCongressMembers.name,
	    	worksFor: $legalEntity.id
	    },
	    identified $usCongressBiographies by $usCongressBiographies.worksFor into {
	       name: $usCongressBiographies.worksFor
	    }
	];

write $person to 'file:///tmp/MappingITTestOutputPersons.json';
write $legalEntity to 'file:///tmp/MappingITTestOutputLegalEntities.json';