using cleansing;

$originalPersons = read from 'MappingIT2TestOriginalPersons.json';

$persons, $companies  = map entities from $originalPersons
	as [
	    identified $originalPersons by $originalPersons.id into {
	    	name: $originalPersons.name,
	    	worksFor: $companies.id
	    },
	    identified $originalPersons by $originalPersons.worksFor into {
	       name: $originalPersons.worksFor
	    }
	];

write $persons to 'file:///tmp/MappingIT2TestOutputPersons.json';
write $companies to 'file:///tmp/MappingIT2TestOutputCompanies.json';