using cleansing;

$usCongressMembers = read from 'src/test/resources/MappingITTestUsCongressMembers.json';
$usCongressBiographies = read from 'src/test/resources/MappingITTestUsCongressBiography.json';

$person, $legalEntity  = map entities of $usCongressMembers, $usCongressBiographies where ($usCongressMembers.biography == $usCongressBiographies.biographyId)
	into [
	    entity $usCongressMembers identified by $usCongressMembers.id with {
	    	name: $usCongressMembers.name,
	    	worksFor: $legalEntity.id
	    },
	    entity $usCongressBiographies identified by $usCongressBiographies.worksFor with {
	       name: $usCongressBiographies.worksFor
	    }
	];

write $person to 'file:///tmp/MappingITTestOutputPersons.json';
write $legalEntity to 'file:///tmp/MappingITTestOutputLegalEntities.json';