using cleansing;

$persons = read from '/src/test/resources/TestData.json';

$persons_scrubbed = scrub $persons with rules {
	_id: required,
	format: hasPattern("\d{4}-\d{4}"),
	number: range(500, 1500),
	whitelist: containedIn(["A", "B", "C"]),
	blacklist: notContainedIn(["D", "E", "F"]),
	illChar: illegalCharacters("%$&")?: removeIllegalCharacters,
	whitespace: [normalize_whitespaces(), illegalCharacters("fo")?: removeIllegalCharacters],
	substr: substring(1,3)
	//type: ofType("int")?: default(0) //excluded temporarily because of syntax discussions
};

write $persons_scrubbed to 'file:///tmp/TestOutput.json';
